#!/bin/bash

# Shaadi Bazaar - Vercel Deployment Script
# This script automates deployment to Vercel

set -e

echo "🚀 Starting Shaadi Bazaar Deployment to Vercel..."

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Step 1: Check prerequisites
echo -e "\n${YELLOW}Step 1: Checking prerequisites...${NC}"

if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm is not installed. Please install Node.js and npm first.${NC}"
    exit 1
fi

if ! command -v git &> /dev/null; then
    echo -e "${RED}❌ git is not installed. Please install git first.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Prerequisites check passed${NC}"

# Step 2: Install Vercel CLI
echo -e "\n${YELLOW}Step 2: Installing Vercel CLI...${NC}"

npm install -g vercel

echo -e "${GREEN}✅ Vercel CLI installed${NC}"

# Step 3: Build locally
echo -e "\n${YELLOW}Step 3: Running local build test...${NC}"

npm run build

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Build failed. Please fix errors and try again.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Build successful${NC}"

# Step 4: Run linting
echo -e "\n${YELLOW}Step 4: Running linter...${NC}"

npm run lint || true

echo -e "${GREEN}✅ Lint check complete${NC}"

# Step 5: Configure environment variables
echo -e "\n${YELLOW}Step 5: Setting up environment variables...${NC}"

read -p "Enter your MongoDB Atlas connection string (MONGODB_URI): " MONGODB_URI
read -p "Enter your JWT secret (JWT_SECRET): " JWT_SECRET
read -p "Enter your Vercel deployment URL or custom domain (NEXT_PUBLIC_API_URL): " API_URL

echo -e "${GREEN}✅ Environment variables configured${NC}"

# Step 6: Deploy to Vercel
echo -e "\n${YELLOW}Step 6: Deploying to Vercel...${NC}"

vercel --prod \
  --env MONGODB_URI="$MONGODB_URI" \
  --env JWT_SECRET="$JWT_SECRET" \
  --env NEXT_PUBLIC_API_URL="$API_URL"

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Deployment failed.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Deployment successful!${NC}"

# Step 7: Verify deployment
echo -e "\n${YELLOW}Step 7: Verifying deployment...${NC}"

sleep 5

if curl -s -f "$API_URL/health" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Health check passed - API is responding${NC}"
else
    echo -e "${YELLOW}⚠️  Health check did not pass. This may be normal if endpoint not configured.${NC}"
fi

echo -e "\n${GREEN}🎉 Deployment complete!${NC}"
echo -e "\nYour app is now live at:"
echo -e "${GREEN}$API_URL${NC}"

echo -e "\n${YELLOW}Next steps:${NC}"
echo "1. Verify all features are working on production"
echo "2. Setup custom domain in Vercel dashboard"
echo "3. Configure DNS records for your domain"
echo "4. Wait 24-48 hours for DNS propagation"
echo "5. SSL certificate will be auto-generated by Vercel"
echo ""
echo "Deployment Documentation: See DEPLOYMENT.md"
